### PR TITLE
add reimbursement guidelines

### LINKED ISSUE #46: explain how to get reimbursed for conference expenses
things to explain (and confirm with Dorit):
- [x] lab members should pay for things themselves, save the receipts, and then submit them for reimbursement after the conference
- [ ] it's best to book hotel/travel as a "personal" (so **not** with a "request ID") expense through [concur.ucsd.edu](https://concur.ucsd.edu) which has docs [here](https://blink.ucsd.edu/travel/concur/index.html)
    advantages: It's easier to get reimbursed for things on concur? If you book it through Concur, you're more likely to be reimbursed for it? And you may get special rates sometimes? But there are some cases where a hotel doesn't show up on Concur
- [x] don't choose a hotel that exceeds $275/night
    - [ ] what if some of the nights exceed $275, but the average across all nights is still below $275? apparently, this isn't ok
- [x] you can get reimbursed for meals so long as you don't spend more than $70 per day
- [ ] you can get reimbursed for travel (by uber or train, for ex) or gas? (by car) and/or overnight parking if you drive yourself somewhere
- [x] if you share a meal (or other expense) with another lab member, it's best if each person pays for themselves instead of you paying for others on their behalf. If you _do_ pay for others, they should venmo you their portion of the cost and all of you should submit an itemized receipt for the meal
- [ ] if you need to fly back from a conference the day after the conference ends (or fly in the day before), you can still get reimbursed for food for that extra day

docs to include:
- [x] #50
- [ ] this link that has lots of useful info: https://blink.ucsd.edu/travel/_files/TravelPolicyHighlights.pdf
- [ ] template spreadsheets for organizing expenses for submission
- [ ] UC San Diego Student Certification for Business-Related Travel form

if anyone else has any questions to ask or anything to add, please mention it here!

### PR DESCRIPTION
**Pull request by aryarm**
resolves #46 

Thanks to @Dorit1976 for creating this helpful doc !

### CODE REVIEW

**Comment by aryarm** [comment]
To preview the changes:

https://gymreklabgithubio--60.org.readthedocs.build/en/60/Conferences.html

**Review by yli091230 — APPROVED** [review]
Thanks @aryarm for updating the reimbursement guidelines. It looks great. One quick question, what does "Raid share-" (between the Meals & TIps and Receipts) mean?

**Comment by aryarm** [comment]
Thanks for approving it, @yli091230 !

And good catch. @Dorit1976 , what does "Raid share-" mean?

**Comment by aryarm** [comment]
I'm going to merge this now so that it appears on the lab wiki

**Pull request merged**
